#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.24.2
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/grub 2.02\+dfsg1-9\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/grub.d/init-select.cfg 2.12\~rc1-5\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_freebsd 2.00-14\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/grub.d/10_hurd 2.00-14\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'grub-common.service' >/dev/null || true
	fi
fi
# End automatically added section
