#! /bin/sh
set -e

if [ "$1" = remove ]; then
    # Remove DEP17 M8 protective diversion
    dpkg-divert --quiet --remove --no-rename --divert "/lib64/ld-linux-x86-64.so.2.usr-is-merged" "/lib64/ld-linux-x86-64.so.2"
fi

# Automatically added by dh_installdebconf/13.24.2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
