#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    pc=$(LC_ALL=C.UTF8 dpkg-query -f '${db:Status-Abbrev} ${binary:Package}\n' -W libpython3.13-minimal \
	| grep -v '^.n' | wc -l)
    if [ "$pc" -lt 1 ]; then
	find /usr/lib/python3.13 -depth -type d -name __pycache__ \
	    | xargs -r rm -rf
	rm -f /etc/python3.13/sitecustomize.py
	rm -rf /etc/python3.13/__pycache__
	if [ -d /etc/python3.13 ]; then
	    rmdir --ignore-fail-on-non-empty /etc/python3.13
	fi
    fi
fi



exit 0
