#!/bin/sh -e

delete_if_md5_matches() {
  local md5

  if [ -e /etc/hosts ]; then
  md5="$(md5sum /etc/hosts | sed -e 's/ .*//')"
  case "$md5" in
    05e70b0d3ac00a2fbc94781871ae9aa8) rm /etc/hosts ;;
  esac
  fi

  if [ -e /etc/networks ]; then
  md5="$(md5sum /etc/networks | sed -e 's/ .*//')"
  case "$md5" in
    d013c6de91b961753d4ba901347aa6c8) rm /etc/networks ;;
  esac
  fi
}

case "$1" in
    purge)
    delete_if_md5_matches
    ;;
esac


